---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
packages = c('scales', 'viridis', 
             'lubridate', 'ggthemes', 
             'gridExtra', 'tidyverse', 
             'readxl', 'knitr',
             'data.table')
```

```{r}
attacks <- read_csv("data/eventlog.csv")
```
```{r}
make_hr_wkday <- function(ts, sc, tz) {
  real_times <- ymd_hms(ts, 
                        tz = tz[1], 
                        quiet = TRUE)
  dt <- data.table(source_country = sc,
                   wkday = weekdays(real_times),
                   hour = hour(real_times))
  return(dt)
}
```

```{r}
wkday_levels <- c('Sunday', 'Monday', 
                  'Tuesday', 'Wednesday', 
                  'Thursday', 'Friday', 
                  'Saturday')
attacks <- attacks %>%
  group_by(tz) %>%
#group_by timezone
  do(make_hr_wkday(.$timestamp, 
                   .$source_country, 
                   .$tz ) ) %>% 
  ungroup() %>%
#in R, data is initially in Character.
  
  mutate(wkday = factor(wkday, 
                        levels = wkday_levels),
         hour  = factor(hour, 
                        levels = 0:23))
#24hour/day intervals
```

```{r}
grouped<-attacks%>%
  count(wkday,hour)%>%
  ungroup()
ggplot(grouped,
       aes(hour,
           wkday,
           fill = n)) +
geom_tile(color = "white",
           size = 0.1) +
# this provide the line  
theme_tufte(base_family = "Helvetica") +
coord_equal()+
scale_fill_viridis(name="# of Events",
                   label=comma) +
labs(x = NULL,
     y= NULL,
     title = "Events per day of week & time of day") +
theme(axis.ticks = element_blank(),
      plot.title = element_text(hjust = 0.5),
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 6) )
```






